* usr/sbin/bootmail, usr/sbin/rootsign:   - add some checks, necessary if running bootmail or rootsign under sudo

diff --git a/usr/sbin/bootmail b/usr/sbin/bootmail
--- a/usr/sbin/bootmail
+++ b/usr/sbin/bootmail
@@ -21,6 +21,17 @@
 
 # Get GPG_OPTS
 . /etc/bootmail/gpg.conf
+PKG=bootmail
+
+# All sorts of things go wrong if you don't own your $HOME dir.
+# This happens under sudo, if you don't use the -H option.
+if [ ! -O "$HOME" ]; then
+        echo "Cannot run $PKG because [$USER] does not own [$HOME]" 1>&2
+        if [ -n "$SUDO_USER" ]; then
+                echo "To run $PKG under sudo, you MUST use 'sudo -H'" 1>&2
+        fi
+        exit 1
+fi
 
 print_mail_text() {
 	# Print the header
diff --git a/usr/sbin/rootsign b/usr/sbin/rootsign
--- a/usr/sbin/rootsign
+++ b/usr/sbin/rootsign
@@ -26,6 +26,17 @@ if [ "$(id -u)" != "0" ]; then
 	exit 13
 fi
 
+PKG=rootsign
+# All sorts of things go wrong if you don't own your $HOME dir.
+# This happens under sudo, if you don't use the -H option.
+if [ ! -O "$HOME" ]; then
+        echo "Cannot run $PKG because [$USER] does not own [$HOME]" 1>&2
+        if [ -n "$SUDO_USER" ]; then
+                echo "To run $PKG under sudo, you MUST use 'sudo -H'" 1>&2
+        fi
+        exit 1
+fi
+
 # Get GPG_OPTS and FROM_MAIL
 . /etc/bootmail/gpg.conf
 
