* etc/bootmail/gpg.conf, usr/sbin/rootsign,   usr/share/man/man8/bootmail.8, usr/share/man/man8/rootsign.8:   - support an optional RECIPIENT_KEYID variable in /etc/bootmail/gpg.conf,     to enable users to encrypt as well as sign messages with the rootsign     utility

diff --git a/usr/sbin/rootsign b/usr/sbin/rootsign
--- a/usr/sbin/rootsign
+++ b/usr/sbin/rootsign
@@ -56,5 +56,22 @@ if ! gpg $GPG_OPTS --list-keys "$FROM_MAIL" >/dev/null 2>&1; then
 	chmod 644 /var/lib/rootsign/rsa.pub
 fi
 
+CLEARSIGN="--clearsign"
+if [ -n "$RECIPIENT_KEYID" ]; then
+	if gpg $GPG_OPTS --list-keys "$RECIPIENT_KEYID" >/dev/null 2>&1; then
+		GPG_OPTS="$GPG_OPTS -e -r $RECIPIENT_KEYID"
+		CLEARSIGN=
+	else
+		if gpg $GPG_OPTS --recv-keys $RECIPIENT_KEYID; then
+			GPG_OPTS="$GPG_OPTS -e -r $RECIPIENT_KEYID"
+			CLEARSIGN=
+		else
+			echo "ERROR: You need to manually import [$RECIPIENT_KEYID]" 1>&2
+			echo "  cat public_key | gpg $GPG_OPTS --import" 1>&2
+			exit 1
+		fi
+	fi
+fi
+
 # Sign stdin
-cat /dev/stdin | gpg $GPG_OPTS -a -s --clearsign
+cat /dev/stdin | gpg $GPG_OPTS -a -s $CLEARSIGN
